image_types = [
    't2.micro',
    't2.small',
    't2.medium',
    't2.large',
    't1.micro',
    'm1.small',
    'm1.medium',
    'm1.large',
    'm1.xlarge',
    'm3.medium',
    'm3.large',
    'm3.xlarge',
    'm3.2xlarge',
    'c1.medium',
    'c1.xlarge',
    'm2.xlarge',
    'm2.2xlarge',
    'm2.4xlarge',
    'cr1.8xlarge',
    'hi1.4xlarge',
    'hs1.8xlarge',
    'cc1.4xlarge',
    'cg1.4xlarge',
    'cc2.8xlarge',
    'g2.2xlarge',
    'c3.large',
    'c3.xlarge',
    'c3.2xlarge',
    'c3.4xlarge',
    'c3.8xlarge',
    'i2.xlarge',
    'i2.2xlarge',
    'i2.4xlarge',
    'i2.8xlarge'
]

image_ids = [
    {'name': 'ami-e7527ed7',
     'user': 'ec2-user'}
]
